### ISSUE TITLE
Remove hardcoded link to my personal bucket

### ISSUE THREAD

**Issue by Ash258** [kidonng/scoop-docs#74]
https://github.com/kidonng/scoop-docs/blob/870db706de7622061d5ea123e57a4098ff7042ab/scripts/index-apps.js#L30

And of course all related stuff around this. No reason to hardcode and expose my **personal** bucket to users

**Comment by kidonng** [comment]
My initial intention was to index all scoop bucket repos (like `rasa/scoop-directory` does) but didn't make it work at the beginning, and I just chose the known buckets and the top 5 buckets in scoop-directory to get started.
Currently the index is no longer updating and I didn't get the time to finish the new index script (which will search for all repos with `scoop-bucket` tag).
If I understand correctly, you want your personal bucket excluded? I will add that in the new script. Indexed content about your bucket will be removed later (I'm about to take a rest). Sorry for the inconvenience.

**Comment by Ash258** [comment]
I just do not want it to be here. Remove it.

**Comment by kidonng** [comment]
Indexed content about your personal bucket has been removed. If you have any other questions, please let me know.
